services:
  dynamic_configuration_controller:
    public: true
    class: DynamicJobTabBundle\Controller\ConfigurationController
    arguments:
      - '@akeneo_batch.job.job_instance_repository'
      